name: rahul-test-hello-action
description: Lorem Ipsum is simply dummy text of the printing and typesetting industry
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
